version: '3.8'
services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - TZ=UTC
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
      - searxng_data:/var/cache/searxng

volumes:
  searxng_data:
